version: '3.8'

services:
  valhalla-build:
    image: ghcr.io/valhalla/valhalla:latest
    container_name: valhalla_builder
    volumes:
      - ./valhalla_data:/valhalla_data
      - ./valhalla_tiles:/valhalla_tiles
      - ./valhalla.json:/etc/valhalla.json
    command: >
      bash -c '
        set -e
        if [ ! -f /valhalla_tiles/valhalla_tiles.tar ]; then
          echo "========================================================================"
          echo "MEMBANGUN VALHALLA TILES DARI PBF. PROSES INI AKAN SANGAT LAMA..."
          echo "Harap tunggu hingga Anda melihat pesan BUILD COMPLETE."
          echo "========================================================================"
          
          # PERBAIKAN: Menambahkan path ke file PBF di sini
          valhalla_build_admins --config /etc/valhalla.json /valhalla_data/indonesia-latest.osm.pbf
          
          valhalla_build_tiles -c /etc/valhalla.json /valhalla_data/indonesia-latest.osm.pbf
          
          echo "========================================================================"
          echo "BUILD COMPLETE. Valhalla tiles telah dibuat di direktori valhalla_tiles."
          echo "========================================================================"
        else
          echo "Valhalla tiles sudah ada. Melewatkan proses pembangunan."
        fi
      '

  valhalla:
    image: ghcr.io/valhalla/valhalla:latest
    container_name: valhalla_server
    depends_on:
      # PERBAIKAN: Menunggu hingga build selesai DENGAN SUKSES
      valhalla-build:
        condition: service_completed_successfully
    ports:
      - "8002:8002"
    volumes:
      - ./valhalla_tiles:/valhalla_tiles
      - ./valhalla.json:/etc/valhalla.json
    command: >
      bash -c '
        echo "======================================="
        echo "MEMULAI LAYANAN VALHALLA PADA PORT 8002"
        echo "======================================="
        valhalla_service /etc/valhalla.json 1
      '
    restart: unless-stopped